# ----------------------------------------------------------------------------------------------------------------------
# Site customization
# ----------------------------------------------------------------------------------------------------------------------
# Any variable here is referenced in layouts/pages as {{site.XXX}} so something like {{site.googleId}}
# ----------------------------------------------------------------------------------------------------------------------

id: oneops.com
name: OneOps
domain: oneops.com
url: http://oneops.com
description: "OneOps"
twitterId: #
googleId: UA-72734811-2
googlePlus: #
slack_url: https://oneops.slack.com/
slack_channel: oneops
slack_register: https://oneops.typeform.com/to/fudwo5
twitter_url: https://twitter.com/One_Ops
github_url: https://github.com/oneops
source_url: https://github.com/oneops/oneops.github.io/tree/master/
oneops_training_url: https://www.youtube.com/playlist?list=PLjDnb0653uBDMBpTBoLVkVtGIDO-P8e3U
walmart_technology_community_url: https://www.youtube.com/channel/UCajgVCGqZ2M9RhULR8Q5Iww
logo: /assets/img/logo.png
cross-site: false
collapseNavDocs: true
display-search-in-header: true
custom-footer: true

# Parameters for CorpusSearch
searchurl: http://search.oneops.com/search
searchname: 'site-oneops-'
#authurl: http://auth.oneops.com/auth
#feedbackurl: http://feedback.oneops.com/feedback

navigation:
 - title: OVERVIEW
   url: /overview/about.html
   context: /overview/
 - title: USER
   url: /user/index.html
   context: /user/
 - title: ADMIN
   url: /admin/index.html
   context: /admin/
 - title: DEVELOPER
   url: /developer/index.html
   context: /developer/
 - title: BLOG
   url: /blog/index.html
   context: /blog/


documentation:
 - title: GENERAL
   url: /general/about
   section: /general
 - title: USER
   url: /user
   section: /user
 - title: ADMIN
   url: /admin
   section: /admin
 - title: DEVELOPER
   url: /developer
   section: /developer

projects:
 - title: About OneOps
   url: /overview/about.html
 - title: Benefits
   url: /overview/benefits.html
 - title: Integrations
   url: /overview/integrations.html
 - title: Case Studies
   url: /overview/case-studies.html
 - title: In the Press
   url: /overview/in-the-press.html
 - title: Training
   url: /overview/training.html
 - title: Documentation
   url: /overview/documentation.html
 - title: Contribute
   url: /overview/contribute.html
 - title: Contact
   url: /overview/contact.html

authors:
  ooteam:
    name: The OneOps Team
    web: http://oneops.com
  bbourquin:
    name: Brett Bourquin
    web: https://github.com/bbourqu
  jvanzyl:
    name: Jason van Zyl
    web: http://twitter.com/jvanzyl
  klohia:
    name: Khushboo Lohia
    web: http://github.com/khushbulohia
  ksaroya:
    name: Kulwinder Saroya
    web: http://github.com/kulgh
  mmoser:
    name: Manfred Moser
    web: http://twitter.com/simpligility


# ----------------------------------------------------------------------------------------------------------------------
# Jekyll
# ----------------------------------------------------------------------------------------------------------------------
defaults:
  -
   scope:
     type: pages
   values:
     permalink: /:path/:basename:output_ext
  -
   scope:
     type: posts
   values:
     permalink: /blog/:year-:month-:day-:title.html

excerpt_separator: <!--more-->

markdown: kramdown
kramddown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

exclude:
  - "*.sh"
  - linkcheck-results.log
  - scripts
