# ----------------------------------------------------------------------------------------------------------------------
# Site customization
# ----------------------------------------------------------------------------------------------------------------------
# Any variable here is referenced in layouts/pages as {{site.XXX}} so something like {{site.googleId}}
# ----------------------------------------------------------------------------------------------------------------------

id: oneops.com
name: OneOps
domain: oneops.com
url: http://oneops.com
description: "OneOps"
twitterId: #
googleId: UA-72734811-2
googlePlus: #
slack_url: https://oneops.slack.com/
slack_channel: oneops
slack_register: https://oneops.typeform.com/to/fudwo5
twitter_url: https://twitter.com/One_Ops
github_url: https://github.com/oneops
oneops_training_url: https://www.youtube.com/playlist?list=PLjDnb0653uBDMBpTBoLVkVtGIDO-P8e3U
walmart_technology_community_url: https://www.youtube.com/channel/UCajgVCGqZ2M9RhULR8Q5Iww
logo: /assets/img/logo.png

excerpt_separator: <!--more-->
permalink: /general/blog/:year-:month-:day-:title.html

# Parameters for CorpusSearch
searchurl: http://search.oneops.com/search
searchname: 'site-oneops-'
#authurl: http://auth.oneops.com/auth
#feedbackurl: http://feedback.oneops.com/feedback

navigation:
 - title: OVERVIEW
   url: /general/about.html
   context: /general/
 - title: USER
   url: /user/index.html
   context: /user/
 - title: ADMIN
   url: /admin/index.html
   context: /admin/
 - title: DEVELOPER
   url: /developer/index.html
   context: /developer/
 - title: BLOG
   url: /general/blog/index.html
   context: /general/blog/


documentation:
 - title: GENERAL
   url: /general/about
   section: /general
 - title: USER
   url: /user
   section: /user
 - title: ADMIN
   url: /admin
   section: /admin
 - title: DEVELOPER
   url: /developer
   section: /developer

projects:
 - title: About OneOps
   url: /general/about.html
 - title: Benefits
   url: /general/benefits.html
 - title: Integrations
   url: /general/integrations.html
 - title: Case Studies
   url: /general/case-studies.html
 - title: In the Press
   url: /general/in-the-press.html
 - title: Training
   url: /general/training.html
 - title: Documentation
   url: /general/documentation.html
 - title: Contribute
   url: /general/contribute.html

authors:
  ooteam:
    name: The OneOps Team
    web: http://oneops.com
  bbourquin:
    name: Brett Bourquin
    web: https://github.com/bbourqu
  jvanzyl:
    name: Jason van Zyl
    web: http://twitter.com/jvanzyl
  klohia:
    name: Khushboo Lohia
    web: http://github.com/khushbulohia
  ksaroya:
    name: Kulwinder Saroya
    web: http://github.com/kulgh
  mmoser:
    name: Manfred Moser
    web: http://twitter.com/simpligility

# ----------------------------------------------------------------------------------------------------------------------
# Theme
# ----------------------------------------------------------------------------------------------------------------------

bootstrapVersion: 3.3.1
#theme: walmart

# ----------------------------------------------------------------------------------------------------------------------
# Jekyll
# ----------------------------------------------------------------------------------------------------------------------
markdown: kramdown
kramddown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

exclude:
  - "*.sh"
  - linkcheck-results.log
  - scripts
